# Generated by Django 4.2 on 2025-11-06 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_accreditationsandcertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='why_choose_icons/')),
                ('heading', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_items', to='dashboard.course')),
            ],
            options={
                'db_table': 'why_choose',
            },
        ),
    ]
