# Generated by Django 4.2 on 2025-11-06 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_whychoose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_image', models.ImageField(blank=True, null=True, upload_to='mentors/')),
                ('mentor_name', models.CharField(max_length=255)),
                ('designation_name', models.CharField(max_length=255)),
                ('experience_text', models.TextField()),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='mentor_company_logos/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='dashboard.course')),
            ],
            options={
                'db_table': 'mentors',
            },
        ),
    ]
