# Generated by Django 4.2 on 2025-11-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_programhighlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('description_list', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='career_assistance/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_assistances', to='dashboard.course')),
            ],
            options={
                'db_table': 'career_assistance',
            },
        ),
    ]
