# Generated by Django 4.2 on 2025-11-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_careerassistance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('placed_company', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=255)),
                ('youtube_testimonial_link', models.URLField(blank=True, max_length=500, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_transitions', to='dashboard.course')),
            ],
            options={
                'db_table': 'career_transitions',
            },
        ),
    ]
