# Generated by Django 4.2 on 2025-11-06 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_careertransition'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurAlumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_logo', models.JSONField(blank=True, default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_alumni', to='dashboard.course')),
            ],
            options={
                'db_table': 'our_alumni',
            },
        ),
    ]
