# Generated by Django 4.2 on 2025-11-06 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_ouralumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnCampusClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('batch_type', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_campus_classes', to='dashboard.course')),
            ],
            options={
                'db_table': 'on_campus_classes',
            },
        ),
    ]
