# Generated by Django 4.2 on 2025-11-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_oncampusclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncampusclass',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
