# Generated by Django 4.2 on 2025-11-08 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_feestructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_for_images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_for', to='dashboard.course')),
            ],
            options={
                'db_table': 'program_for',
            },
        ),
    ]
