# Generated by Django 4.2 on 2025-11-08 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_programfor'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyWhiteScholars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('images', models.JSONField(blank=True, default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_white_scholars', to='dashboard.course')),
            ],
            options={
                'db_table': 'why_white_scholars',
            },
        ),
    ]
