# Generated by Django 4.2 on 2025-11-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_whywhitescholars'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenOurExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_links', models.JSONField(blank=True, default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_our_expert', to='dashboard.course')),
            ],
            options={
                'db_table': 'listen_our_expert',
            },
        ),
    ]
