# Generated by Django 4.2 on 2025-11-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_listenourexpert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenourexpert',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_our_experts', to='dashboard.course'),
        ),
    ]
