# Generated by Django 4.2 on 2025-11-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_listenourexpert_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncampusclass',
            name='class_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
