# Generated by Django 4.2 on 2025-11-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_oncampusclass_class_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
