# Generated by Django 4.2 on 2025-11-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_course_meta_description_course_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
