# Generated by Django 5.2.5 on 2026-02-11 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerassistance',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='careerassistance',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='careertransition',
            name='achievement_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='careertransition',
            name='from_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='careertransition',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='career_transitions/'),
        ),
        migrations.AddField(
            model_name='careertransition',
            name='profile_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='careertransition',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='careertransition',
            name='story_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='careertransition',
            name='to_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='brochure_pdf',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='cta_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='cta_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyhighlight',
            name='logo_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='keyhighlight',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mentor',
            name='company_logo_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mentor',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='oncampusclass',
            name='cta_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='oncampusclass',
            name='cta_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='oncampusclass',
            name='seats_left_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='oncampusclass',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programfor',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='programfor',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programhighlight',
            name='description_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programhighlight',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='programhighlight',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whychoose',
            name='icon_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='whychoose',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AccreditationLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='accreditations_certifications/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditation_logos', to='dashboard.course')),
            ],
            options={
                'db_table': 'accreditation_logos',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AlumniLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='alumni_logos/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_logos', to='dashboard.course')),
            ],
            options={
                'db_table': 'alumni_logos',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CareerTransitionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='career_transition_stats/')),
                ('icon_alt', models.CharField(blank=True, max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_transition_stats', to='dashboard.course')),
            ],
            options={
                'db_table': 'career_transition_stats',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CertificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='dashboard.course')),
            ],
            options={
                'db_table': 'certifications',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CourseHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(blank=True, max_length=100)),
                ('badge_icon', models.ImageField(blank=True, null=True, upload_to='hero_badges/')),
                ('badge_icon_alt', models.CharField(blank=True, max_length=255)),
                ('award_text', models.CharField(blank=True, max_length=255)),
                ('award_logo', models.ImageField(blank=True, null=True, upload_to='hero_awards/')),
                ('award_logo_alt', models.CharField(blank=True, max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.CharField(blank=True, max_length=255)),
                ('description_html', models.TextField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
                ('hero_image_alt', models.CharField(blank=True, max_length=255)),
                ('hero_video_url', models.URLField(blank=True, max_length=500)),
                ('hero_video_thumbnail', models.ImageField(blank=True, null=True, upload_to='hero_videos/')),
                ('hero_video_thumbnail_alt', models.CharField(blank=True, max_length=255)),
                ('collaboration_heading', models.CharField(blank=True, max_length=255)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='dashboard.course')),
            ],
            options={
                'db_table': 'course_hero',
            },
        ),
        migrations.CreateModel(
            name='CourseHeroButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('style', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('ghost', 'Ghost')], default='primary', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_buttons', to='dashboard.course')),
            ],
            options={
                'db_table': 'hero_buttons',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CourseOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_html', models.TextField(blank=True, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_overview', to='dashboard.course')),
            ],
            options={
                'db_table': 'course_overview',
            },
        ),
        migrations.CreateModel(
            name='CourseOverviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer_html', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_overview_items', to='dashboard.course')),
            ],
            options={
                'db_table': 'course_overview_items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_modules', to='dashboard.course')),
            ],
            options={
                'db_table': 'curriculum_modules',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_us_title', models.CharField(blank=True, max_length=255)),
                ('call_us_phone', models.CharField(blank=True, max_length=50)),
                ('call_us_button_label', models.CharField(blank=True, max_length=100)),
                ('call_us_button_url', models.URLField(blank=True, max_length=500)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_section', to='dashboard.course')),
            ],
            options={
                'db_table': 'curriculum_section',
            },
        ),
        migrations.CreateModel(
            name='ExpertTalkVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='expert_talks/')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_talk_videos', to='dashboard.course')),
            ],
            options={
                'db_table': 'expert_talk_videos',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer_html', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='dashboard.course')),
            ],
            options={
                'db_table': 'faq_items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FaqSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.CharField(blank=True, max_length=500)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faq_section', to='dashboard.course')),
            ],
            options={
                'db_table': 'faq_section',
            },
        ),
        migrations.CreateModel(
            name='HeroCollaborationLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='collaboration_logos/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_collaboration_logos', to='dashboard.course')),
            ],
            options={
                'db_table': 'hero_collaboration_logos',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HeroHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_highlights', to='dashboard.course')),
            ],
            options={
                'db_table': 'hero_highlights',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HiringLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hiring_logos/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_logos', to='dashboard.course')),
            ],
            options={
                'db_table': 'hiring_logos',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LearnerJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='learner_journey/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_journey', to='dashboard.course')),
            ],
            options={
                'db_table': 'learner_journey',
            },
        ),
        migrations.CreateModel(
            name='LiveDemoCta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('button_label', models.CharField(max_length=100)),
                ('button_url', models.URLField(max_length=500)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_demo_cta', to='dashboard.course')),
            ],
            options={
                'db_table': 'live_demo_cta',
            },
        ),
        migrations.CreateModel(
            name='OnCampusSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_cta_text', models.CharField(blank=True, max_length=255)),
                ('bottom_cta_label', models.CharField(blank=True, max_length=100)),
                ('bottom_cta_url', models.URLField(blank=True, max_length=500)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='on_campus_section', to='dashboard.course')),
            ],
            options={
                'db_table': 'on_campus_section',
            },
        ),
        migrations.CreateModel(
            name='RelatedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='related_articles/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_articles', to='dashboard.course')),
            ],
            options={
                'db_table': 'related_articles',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RelatedArticlesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_more_label', models.CharField(blank=True, max_length=100)),
                ('load_more_url', models.URLField(blank=True, max_length=500)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_articles_section', to='dashboard.course')),
            ],
            options={
                'db_table': 'related_articles_section',
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('text', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('avatar_alt', models.CharField(blank=True, max_length=255)),
                ('review_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='dashboard.course')),
            ],
            options={
                'db_table': 'review_items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('total_reviews', models.PositiveIntegerField(blank=True, null=True)),
                ('summary_title', models.CharField(blank=True, max_length=255)),
                ('summary_text', models.CharField(blank=True, max_length=500)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.URLField(blank=True, max_length=500)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_section', to='dashboard.course')),
            ],
            options={
                'db_table': 'review_section',
            },
        ),
        migrations.CreateModel(
            name='SalaryDesignationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('min_values', models.JSONField(blank=True, default=list)),
                ('max_values', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_designations', to='dashboard.course')),
            ],
            options={
                'db_table': 'salary_designations',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SalaryTrendSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_trend_section', to='dashboard.course')),
            ],
            options={
                'db_table': 'salary_trend_section',
            },
        ),
        migrations.CreateModel(
            name='ScopeBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_bullets', to='dashboard.course')),
            ],
            options={
                'db_table': 'scope_bullets',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ScopeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_html', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scope_images/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scope_section', to='dashboard.course')),
            ],
            options={
                'db_table': 'scope_section',
            },
        ),
        migrations.CreateModel(
            name='WhyWhiteScholarsBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_white_scholars_bullets', to='dashboard.course')),
            ],
            options={
                'db_table': 'why_white_scholars_bullets',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='WhyWhiteScholarsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='why_white_scholars_images/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_white_scholars_images', to='dashboard.course')),
            ],
            options={
                'db_table': 'why_white_scholars_images',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('hero', 'Hero'), ('key_highlights', 'Key Highlights'), ('accreditations', 'Accreditations'), ('why_choose', 'Why Choose'), ('live_demo', 'Live Demo CTA'), ('course_overview', 'Course Overview'), ('mentors', 'Mentors'), ('program_highlights', 'Program Highlights'), ('learner_journey', 'Learner Journey'), ('curriculum', 'Curriculum'), ('career_assistance', 'Career Assistance'), ('career_transitions', 'Career Transitions'), ('alumni', 'Our Alumni'), ('on_campus', 'On Campus Classes'), ('fee_structure', 'Fee Structure'), ('program_for', 'Program For'), ('why_white_scholars', 'Why WhiteScholars'), ('expert_talks', 'Expert Talks'), ('salary_trends', 'Salary Trends'), ('scope', 'Scope'), ('related_articles', 'Related Articles'), ('certifications', 'Certifications'), ('reviews', 'Reviews'), ('faqs', 'FAQs'), ('cta_ready', 'CTA Ready'), ('cta_discover', 'CTA Discover'), ('cta_confused', 'CTA Confused')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_order', to='dashboard.course')),
            ],
            options={
                'db_table': 'course_sections',
                'ordering': ['sort_order'],
                'unique_together': {('course', 'key')},
            },
        ),
        migrations.CreateModel(
            name='LeadCta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('ready', 'Ready to Start'), ('discover', 'Discover Secrets'), ('confused', 'Still Confused')], max_length=20)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('description_html', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lead_ctas/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_ctas', to='dashboard.course')),
            ],
            options={
                'db_table': 'lead_ctas',
                'unique_together': {('course', 'key')},
            },
        ),
    ]
